### PR TITLE
Simpler component data, or gates, orient-able components and select-able wires

### PR DESCRIPTION
**Pull request by NogginBops**
Changes how components and instances are stored to make it a lot simpler.
This pr adds the ability to place or gates (and implements the drawing of them).
It also tweaks the look of not gates.
Added a MouseMove and KeyPress event to ITool to make the component placement tool work.
Made the select tool be able to select and delete wires.
This pr also contains some general cleanup of dead code.

### CODE REVIEW

**Comment by NogginBops** [comment]
@weerox can I get a review?

**Comment by weerox** [comment]
Fetched the PR and tested it, love the OR gate! Also did a quick scan through the code and noticed that there now exists a number of other components. Should they be added to the toolbar too or should they be accessed by other means?

**Comment by NogginBops** [comment]
I think that a collection of common gates should be available in the toolbar. Stuff like and, or, xor and so on, but the rest of the components should be available in the components view.

**Comment by NogginBops** [comment]
I will merge this without a proper review after a decision that I should merge this in the project discord.

**Pull request merged**
